### ISSUE TITLE
Incombatible with LTN

### ISSUE THREAD

**Issue by 0ptera** [Jelmergu/factorio-there-is-my-ghost#2]
When used together with LTN, hand placing LTN train stopsy over a ghost only spawns the scripted additional entities, but doesn't place stop entity triggering my spawn events.

~~To get a proper 3 entity LTN stop you have to place the stop a 2nd time.~~
This causes desyncs in MP as well.  https://github.com/Yousei9/Logistic-Train-Network/issues/120

Update:
I see the stop entity in on_built_entity / on_robot_built_entity in LTN. After those events your mod seems to remove it, causing my IO entities to become orphaned.

**Comment by Jelmergu** [comment]
Yes, I discoverd this on my own as well, I am working on a fix for it, which will probably be that I just prevent this mod from working on your entities

**Comment by 0ptera** [comment]
A good practice with github is to add issue numbers like #2 in commit comments.
Github will then automatically add a link to that commit in the issue and notify everyone from the issue thread about the commit.

The obvious bug seems to be gone now. Hopefully the mp desyncs with it.

You might also want to add the script built entities to your blacklist:
logistic-train-stop-input
logistic-train-stop-output
logistic-train-stop-lamp-control
