### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ThorianDragonTamer** [Jelmergu/factorio-there-is-my-ghost#4]
![ghost bug](https://user-images.githubusercontent.com/47370376/53839324-7ee12d80-3f54-11e9-8e77-53ab05784e27.PNG)

Ran into this bug on my modded playthrough experimental .17

**Comment by Jelmergu** [comment]
yeah, just ran into the same bug. I added a function that was supposed to run on_init, but didn't call it

**Comment by ThorianDragonTamer** [comment]
thanks for the response!
